// <auto-generated />
using System;
using DBA.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(GymManagementSystemDBContext))]
    partial class GymManagementSystemDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Account", b =>
                {
                    b.Property<string>("AccountCode")
                        .HasColumnType("Varchar(10)")
                        .HasColumnOrder(0);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .HasColumnType("Char(10)")
                        .HasColumnOrder(1);

                    b.Property<string>("IdNumber")
                        .HasMaxLength(12)
                        .HasColumnType("Char(12)")
                        .HasColumnOrder(2);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LivingAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SalaryCode")
                        .IsRequired()
                        .HasColumnType("Varchar(5)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("Varchar(10)");

                    b.HasKey("AccountCode", "PhoneNumber", "IdNumber");

                    b.HasIndex("RoleId");

                    b.HasIndex("SalaryCode");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Models.Branch", b =>
                {
                    b.Property<string>("BranchCode")
                        .HasColumnType("Varchar(6)")
                        .HasColumnOrder(0);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<string>("AdminUpdate")
                        .IsRequired()
                        .HasColumnType("Varchar(10)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("QuantityOfPTs")
                        .HasColumnType("int");

                    b.Property<int>("QuantityOfStaffs")
                        .HasColumnType("int");

                    b.Property<int>("QuantityOfWorkers")
                        .HasColumnType("int");

                    b.HasKey("BranchCode", "Address");

                    b.HasIndex("AdminUpdate");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Models.Customer", b =>
                {
                    b.Property<string>("CustomerCode")
                        .HasColumnType("Varchar(12)")
                        .HasColumnOrder(0);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("Char(10)")
                        .HasColumnOrder(1);

                    b.Property<string>("BannedReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("Varchar(6)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("Varchar(10)");

                    b.HasKey("CustomerCode", "PhoneNumber");

                    b.HasIndex("BranchCode");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Models.CustomersVoucher", b =>
                {
                    b.Property<int>("OrderNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderNumber"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("Varchar(12)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PackageCode")
                        .IsRequired()
                        .HasColumnType("Varchar(5)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("Varchar(10)");

                    b.HasKey("OrderNumber");

                    b.HasIndex("CustomerCode");

                    b.HasIndex("PackageCode");

                    b.ToTable("CustomersVouchers");
                });

            modelBuilder.Entity("Models.EmployeeSalary", b =>
                {
                    b.Property<Guid>("EmpSalCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasColumnType("Varchar(10)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("Month")
                        .HasColumnType("date");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceTotals")
                        .HasColumnType("Money");

                    b.Property<byte[]>("ProofImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("WorkDays")
                        .HasColumnType("int");

                    b.HasKey("EmpSalCode");

                    b.HasIndex("AccountCode");

                    b.ToTable("EmployeeSalaries");
                });

            modelBuilder.Entity("Models.Equipment", b =>
                {
                    b.Property<string>("EquipCode")
                        .HasColumnType("Varchar(10)");

                    b.Property<string>("AdminUpdate")
                        .IsRequired()
                        .HasColumnType("Varchar(10)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("Varchar(6)");

                    b.Property<string>("EquipName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReceived")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffUpdate")
                        .HasColumnType("Varchar(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EquipCode");

                    b.HasIndex("BranchCode");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("Models.Fine", b =>
                {
                    b.Property<Guid>("FineCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("Varchar(12)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompensated")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("Varchar(10)");

                    b.HasKey("FineCode");

                    b.HasIndex("CustomerCode");

                    b.ToTable("Fines");
                });

            modelBuilder.Entity("Models.Role", b =>
                {
                    b.Property<int>("OrderNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderNumber"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderNumber");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Models.Salary", b =>
                {
                    b.Property<string>("SalaryCode")
                        .HasColumnType("Varchar(5)")
                        .HasColumnOrder(0);

                    b.Property<string>("SalaryType")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<decimal>("PricesApply")
                        .HasColumnType("Money");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SalaryCode", "SalaryType");

                    b.ToTable("Salaries");
                });

            modelBuilder.Entity("Models.ServicePackage", b =>
                {
                    b.Property<string>("PackageCode")
                        .HasColumnType("Varchar(5)")
                        .HasColumnOrder(0);

                    b.Property<string>("PackageName")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<string>("AdminUpdate")
                        .IsRequired()
                        .HasColumnType("Varchar(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MemberQuantity")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfDays")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("Money");

                    b.HasKey("PackageCode", "PackageName");

                    b.ToTable("ServicePackages");
                });

            modelBuilder.Entity("Models.WorkingCheck", b =>
                {
                    b.Property<int>("OrderNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderNumber"));

                    b.Property<DateTime>("CheckDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CheckOf")
                        .IsRequired()
                        .HasColumnType("Varchar(10)");

                    b.Property<bool>("IsCheckIn")
                        .HasColumnType("bit");

                    b.HasKey("OrderNumber");

                    b.HasIndex("CheckOf");

                    b.ToTable("WorkingChecks");
                });

            modelBuilder.Entity("Models.Account", b =>
                {
                    b.HasOne("Models.Role", "role")
                        .WithMany("accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Salary", "salary")
                        .WithMany("account")
                        .HasForeignKey("SalaryCode")
                        .HasPrincipalKey("SalaryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");

                    b.Navigation("salary");
                });

            modelBuilder.Entity("Models.Branch", b =>
                {
                    b.HasOne("Models.Account", "account")
                        .WithMany("branches")
                        .HasForeignKey("AdminUpdate")
                        .HasPrincipalKey("AccountCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("account");
                });

            modelBuilder.Entity("Models.Customer", b =>
                {
                    b.HasOne("Models.Branch", "branch")
                        .WithMany("customers")
                        .HasForeignKey("BranchCode")
                        .HasPrincipalKey("BranchCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("branch");
                });

            modelBuilder.Entity("Models.CustomersVoucher", b =>
                {
                    b.HasOne("Models.Customer", "customer")
                        .WithMany("customersVouchers")
                        .HasForeignKey("CustomerCode")
                        .HasPrincipalKey("CustomerCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.ServicePackage", "servicePackage")
                        .WithMany("customersVoucher")
                        .HasForeignKey("PackageCode")
                        .HasPrincipalKey("PackageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer");

                    b.Navigation("servicePackage");
                });

            modelBuilder.Entity("Models.EmployeeSalary", b =>
                {
                    b.HasOne("Models.Account", "account")
                        .WithMany("employeeSalaries")
                        .HasForeignKey("AccountCode")
                        .HasPrincipalKey("AccountCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("account");
                });

            modelBuilder.Entity("Models.Equipment", b =>
                {
                    b.HasOne("Models.Branch", "branch")
                        .WithMany("equipment")
                        .HasForeignKey("BranchCode")
                        .HasPrincipalKey("BranchCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("branch");
                });

            modelBuilder.Entity("Models.Fine", b =>
                {
                    b.HasOne("Models.Customer", "customer")
                        .WithMany("fines")
                        .HasForeignKey("CustomerCode")
                        .HasPrincipalKey("CustomerCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer");
                });

            modelBuilder.Entity("Models.WorkingCheck", b =>
                {
                    b.HasOne("Models.Account", "account")
                        .WithMany("workingChecks")
                        .HasForeignKey("CheckOf")
                        .HasPrincipalKey("AccountCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("account");
                });

            modelBuilder.Entity("Models.Account", b =>
                {
                    b.Navigation("branches");

                    b.Navigation("employeeSalaries");

                    b.Navigation("workingChecks");
                });

            modelBuilder.Entity("Models.Branch", b =>
                {
                    b.Navigation("customers");

                    b.Navigation("equipment");
                });

            modelBuilder.Entity("Models.Customer", b =>
                {
                    b.Navigation("customersVouchers");

                    b.Navigation("fines");
                });

            modelBuilder.Entity("Models.Role", b =>
                {
                    b.Navigation("accounts");
                });

            modelBuilder.Entity("Models.Salary", b =>
                {
                    b.Navigation("account");
                });

            modelBuilder.Entity("Models.ServicePackage", b =>
                {
                    b.Navigation("customersVoucher");
                });
#pragma warning restore 612, 618
        }
    }
}
